### ISSUE TITLE
Github metadata

### ISSUE THREAD

**Issue by nbenn** [ropensci/infx#9]
@sckott I cannot figure out how to change to url in the github metadata field at the top of the repo page. I think I lost the needed privileges due to the move. How do I go about this? Or could you change the url from https://nbenn.github.io/infx to https://ropensci.github.io/infx?

**Comment by sckott** [comment]
try again, i needed to bump up permissions after you accepted the invittation to the team

**Comment by nbenn** [comment]
thanks!
